name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker test image
        run: docker build -t latest_test --target test .

      - name: Run tests on container
        run: docker run latest_test

      - name: Build Docker production image
        run: docker build -t latest --target production .